# Generated by Django 3.2.3 on 2021-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210712_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='expotoken',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
