# Generated by Django 3.1.7 on 2021-05-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
