# Generated by Django 3.2.3 on 2021-06-04 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='invites_sent',
            field=models.ManyToManyField(related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
