# Generated by Django 3.2.3 on 2021-06-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_events_invites_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='addr',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='max_attendees',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
