# Generated by Django 3.2.3 on 2021-06-23 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_auto_20210615_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='invites_sent',
        ),
        migrations.AddField(
            model_name='events',
            name='invites',
            field=models.ManyToManyField(related_name='join_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
