# Generated by Django 3.2.3 on 2021-06-26 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0004_auto_20210623_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='invites',
            field=models.ManyToManyField(related_name='requesting_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
