# Generated by Django 3.2.3 on 2021-07-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_events_invites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='desc',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
