# Generated by Django 3.2.3 on 2021-07-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_profile_invites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='title',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='desc',
        ),
    ]
