# Generated by Django 3.1.7 on 2021-05-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('home', '0003_auto_20210425_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invites',
            field=models.ManyToManyField(to='event.Events'),
        ),
    ]
