# Generated by Django 3.2.3 on 2021-07-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_posts_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.CharField(max_length=100),
        ),
    ]
